services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - user-service
      - task-service

  user-service:
    build: ./user-service
    env_file:
      - user-service/.env
    networks:
      - my-network
    depends_on:
      - mongodb
      - rabbitmq

  task-service:
    build: ./task-service
    env_file:
      - task-service/.env
    networks:
      - my-network
    depends_on:
      - mongodb

  notification-service:
    build: ./notification-service
    networks:
      - my-network
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.8-management"
    ports:
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/.docker-conf/mongodb/data/:/data/db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge